/**
 * Conditional configuration.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import { $env } from '../../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';

/**
 * Configures conditionals.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Conditional configuration.
 */
export default async ({ mode, command, wranglerMode, appType }) => {
    // Determines a production-like mode.

    const inProdLikeMode = ['prod', 'stage'].includes(mode) || ('dev' === mode && 'dev' === wranglerMode);

    // Determines whether to enable sourcemaps.

    const sourcemapsEnable = ['dev'].includes(mode);

    // Determines whether to enable minification.

    const minifyEnable = !['lib'].includes(appType) && inProdLikeMode;

    // Determines whether to enable prefresh.

    const prefreshEnable = $env.test('VITE_PREFRESH_ENABLE') && 'serve' === command && 'dev' === mode && ['spa', 'mpa'].includes(appType) && !$env.test('VITEST');

    // Returns configuration.

    return { inProdLikeMode, sourcemapsEnable, minifyEnable, prefreshEnable };
};
