##
# Dependabot configuration.
#
# GitHub is aware of this config file's location.
#
# @note CUSTOM EDITS ONLY PLEASE!
# @note In the future this file will be updated automatically.
# @note Only `<custom:start.../custom:end>` will be preserved below.
##

version: 2

registries:
    registry-npmjs-org:
        type: npm-registry
        url: https://registry.npmjs.org
        token: ${{secrets.USER_NPM_TOKEN}}

updates:
    - package-ecosystem: npm
      directory: /
      registries:
          - registry-npmjs-org
      labels:
          - suggestion
          - robotic
      schedule:
          interval: daily
      open-pull-requests-limit: 5

    - package-ecosystem: github-actions
      directory: /
      labels:
          - suggestion
          - robotic
      schedule:
          interval: daily
      open-pull-requests-limit: 5
#
##
# Customizations
# <custom:start>

# </custom:end>
