/**
 * MDX plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@mdx-js/rollup
 */

import pluginConfig from '@mdx-js/rollup';
import path from 'node:path';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures MDX plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX plugin.
 */
export default async (/* {} */) => {
    return pluginConfig(await config({}));
};

/**
 * Produces MDX plugin configuration.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX plugin configuration.
 */
export const config = async (/* {} */) => ({
    exclude: [
        ...new Set([
            ...u.omit.localIgnores, //
            ...u.omit.logIgnores,
            ...u.omit.backupIgnores,
            ...u.omit.patchIgnores,
            ...u.omit.editorIgnores,
            ...u.omit.toolingIgnores,
            ...u.omit.pkgIgnores,
            ...u.omit.vcsIgnores,
            ...u.omit.osIgnores,
            ...u.omit.dotIgnores,
            ...u.omit.dtsIgnores,
            ...u.omit.configIgnores,
            ...u.omit.lockIgnores,
            ...u.omit.devIgnores,
            ...u.omit.distIgnores,
            ...u.omit.docIgnores,
        ]),
    ],
    include: [
        '**/*.' +
            u.exts.asBracedGlob([
                ...u.exts.byVSCodeLang.markdown, // Single default export only.
                ...u.exts.byVSCodeLang.mdx, // Default + potentially other exports.
            ]),
    ],
    ...(await (await import(path.resolve(u.projDir, './mdx.config.mjs'))).default()),
});
