/**
 * Prettier config file.
 *
 * Prettier is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://prettier.io/docs/en/configuration.html
 */
/* eslint-env es2021, node */

/**
 * Base config.
 */
const baseConfig = {
	/**
	 * Plugins.
	 *
	 * @note We use a bunch.
	 * @note https://o5p.me/xCUiHS
	 */
	pluginSearchDirs: false,
	plugins: [
		'prettier-plugin-jsdoc', //
		'prettier-plugin-ini',
		'prettier-plugin-properties',
		'@prettier/plugin-xml',
		'@prettier/plugin-php',
		'prettier-plugin-sql',
		'@prettier/plugin-ruby',
		'prettier-plugin-sh',
	],

	/**
	 * Standard options.
	 *
	 * @note We define them all.
	 * @note https://o5p.me/mmdRUm
	 */
	arrowParens: 'always',
	bracketSameLine: false,
	bracketSpacing: true,
	embeddedLanguageFormatting: 'auto',
	endOfLine: 'lf',
	htmlWhitespaceSensitivity: 'css',
	insertPragma: false,
	jsxSingleQuote: true,
	printWidth: 180,
	proseWrap: 'preserve',
	quoteProps: 'preserve',
	requirePragma: false,
	semi: true,
	singleAttributePerLine: false,
	singleQuote: true,
	tabWidth: 4,
	trailingComma: 'all',
	useTabs: true,
	vueIndentScriptAndStyle: true,
};

/**
 * Composition.
 */
module.exports = {
	...baseConfig,
	overrides: [
		{
			/**
			 * Enforce JSON parser.
			 *
			 * @see https://o5p.me/sj8jjz
			 */
			files: ['*.json'],
			options: {
				parser: 'json', // Not `json-stringify`.
			},
		},
		{
			/**
			 * JSDoc plugin options.
			 *
			 * @see https://o5p.me/dTTfse
			 */
			files: ['*.{js,jsx,cjs,cjsx,mjs,mjsx,ts,tsx,cts,ctsx,mts,mtsx,node}'],
			options: {
				jsdocAddDefaultToDescription: false,
				jsdocCapitalizeDescription: true,
				jsdocDescriptionTag: false,
				jsdocDescriptionWithDot: true,
				jsdocKeepUnParseAbleExampleIndent: false,
				jsdocLineWrappingStyle: 'greedy',
				jsdocPreferCodeFences: false,
				jsdocPrintWidth: 120,
				jsdocSeparateReturnsFromParam: true,
				jsdocSeparateTagGroups: true,
				jsdocSingleLineComment: false,
				jsdocSpaces: 1,
				jsdocVerticalAlignment: true,
				tsdoc: false,
			},
		},
		{
			/**
			 * PHP plugin options.
			 *
			 * @see https://o5p.me/BHsZj8
			 */
			files: ['*.php'],
			options: {
				parser: 'php',
				braceStyle: '1tbs',
				phpVersion: '8.1',
				trailingCommaPHP: true,
			},
		},
		{
			/**
			 * Ruby plugin options.
			 *
			 * @see https://o5p.me/tuKNvU
			 */
			files: ['*.rb'],
			options: {
				parser: 'ruby',
				rubyPlugins: '',
				rubySingleQuote: true,
			},
		},
		{
			/**
			 * SH plugin options.
			 *
			 * @see https://o5p.me/D0rlOV
			 */
			files: ['*.bash', '{,*.}Dockerfile'],
			options: {
				parser: 'sh',
				binaryNextLine: false,
				experimentalWasm: false,
				functionNextLine: false,
				indent: 4,
				keepComments: true,
				keepPadding: false,
				minify: false,
				spaceRedirects: true,
				stopAt: undefined,
				switchCaseIndent: true,
				variant: 0, // Bash.
			},
		},
		{
			/**
			 * SQL plugin options.
			 *
			 * @see https://o5p.me/kYq5bx
			 */
			files: ['*.sql'],
			options: {
				parser: 'sql',
				commaPosition: 'after',
				database: 'mysql',
				denseOperators: false,
				expressionWidth: 180,
				formatter: 'sql-formatter',
				indentStyle: 'standard',
				keywordCase: 'upper',
				language: 'sql',
				linesBetweenQueries: 1,
				logicalOperatorNewline: 'before',
				newlineBeforeSemicolon: false,
				params: Object,
				paramTypes: Object,
				tabulateAlias: false,
				type: 'table',
			},
		},
		{
			/**
			 * XML plugin options.
			 *
			 * @see https://o5p.me/OiLPzn
			 */
			files: ['*.xml'],
			options: {
				parser: 'xml',
				xmlSelfClosingSpace: true,
				xmlWhitespaceSensitivity: 'ignore',
			},
		},
		{
			/**
			 * INI plugin options.
			 *
			 * @see https://o5p.me/1fqazf
			 */
			files: ['*.ini'],
			options: {
				parser: 'ini',
				iniSpaceAroundEquals: true,
			},
		},
		{
			/**
			 * Properties plugin options.
			 *
			 * @see https://o5p.me/IyzRSp
			 */
			files: ['*.properties', '*.env{,.*}'],
			options: {
				parser: 'dot-properties',
				keySeparator: '=',
				escapeNonLatin1: false,
			},
		},
		{
			/**
			 * YAML spec options.
			 *
			 * @see https://o5p.me/jJH2xY
			 */
			files: ['*.yml', '*.yaml'],
			options: {
				tabWidth: 2,
				useTabs: false,
			},
		},
	],
};
