##
# Wrangler configuration.
#
# @note Wrangler is aware of this config file's location.
#
# @note CUSTOM EDITS ONLY PLEASE!
# In the future this file will be updated automatically.
# Only `<custom:start.../custom:end>` will be preserved below.
##
compatibility_date = "2022-08-04"
compatibility_flags = ["global_navigator"]

main = "./dst/index.js"
build = { command = "npm run build:prod" }
vars = { IS_C10N = "cf=prod&cfw=prod" }
account_id = "f1176464a976947aa5665d989814a4b1"

##
# Customizations
# <custom:start>

name = "clevercanyon.utilities.webw"
routes = ["clevercanyon.utilities.webw/*"]

# </custom:end>

[env.dev]
workers_dev = true
vars = { IS_C10N = "cf=dev&cfw=dev" }
