/**
 * Basic configuration.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://vite.dev/config/shared-options.html
 */

import path from 'node:path';
import { $json, $obj, $url } from '../../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures basics.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Basic configuration.
 */
export default async ({ isSSRBuild, appEnvPrefixes, appBaseURLResolvedNTS, staticDefs, cacheDir, appType, pkgUpdates }) => {
    return {
        basicConfig: {
            c10n: { pkg: u.pkg(), pkgUpdates },
            define: $obj.map(staticDefs, (v) => $json.stringify(v)),

            root: u.srcDir, // Absolute path where entry indexes live.
            cacheDir: cacheDir, // Where Vite stores cache files.

            publicDir: isSSRBuild ? false : path.relative(u.srcDir, u.cargoDir),
            base: appBaseURLResolvedNTS ? $url.toPath(appBaseURLResolvedNTS) : '/',

            envDir: path.relative(u.srcDir, u.envsDir), // Relative to `root` directory.
            envPrefix: appEnvPrefixes, // Env vars w/ these prefixes become part of the app.

            appType: ['spa', 'mpa'].includes(appType) ? appType : 'custom',
        },
    };
};
