/**
 * Mode-related configuration.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://vite.dev/config/shared-options.html#mode
 */

import { $env } from '../../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';

/**
 * Configures mode-related vars.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Mode-related configuration.
 */
export default async ({ viteMode, viteCommand, viteIsSsrBuild }) => {
    let mode = viteMode; // Initialize.

    if ($env.test('APP_IS_VITE') /* Child process of Vite? */) {
        mode = $env.get('APP_IS_VITE', { type: 'string' }).split('=')[1] || mode;
    }
    return {
        mode,
        command: viteCommand,
        isSSRBuild: viteIsSsrBuild,
        wranglerMode: $env.get('VITE_WRANGLER_MODE', { type: 'string' }),
        vitestSandboxEnable: $env.test('VITEST') && $env.test('VITEST_SANDBOX_ENABLE'),
        vitestExamplesEnable: $env.test('VITEST') && $env.test('VITEST_EXAMPLES_ENABLE'),
    };
};
