/**
 * Tailwind CSS config file.
 *
 * @note Tailwind is not aware of this config file's location.
 * @see https://tailwindcss.com/docs/configuration
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This entire file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

/* @formatter:ignore
-----------------------------------------------------------------------------------------------------------------------
Example `index.scss` starter file contents:
-----------------------------------------------------------------------------------------------------------------------
@import 'https://fonts.googleapis.com/css2?family=Georama:ital,wght@0,100..900;1,100..900&display=swap';

@tailwind base;
@tailwind components;
@tailwind utilities;
------------------------------------------------------------------------------------------------- @formatter:/ignore */

const path    = require( 'node:path' );
const projDir = path.resolve( __dirname, '../../..' );

module.exports = {
	theme   : {
		fontFamily : {
			sans  : [ 'Georama', 'sans-serif' ],
			serif : [ 'Georgia', 'serif' ],
		},
	},
	content : [
		path.resolve( projDir, './src/*.{md,xml,html,shtml,php,js,cjs,mjs,jsx,ts,tsx,ejs}' ),
		path.resolve( projDir, './src/**/*.{md,xml,html,shtml,php,js,cjs,mjs,jsx,ts,tsx,ejs}' ),
	],
};
