/**
 * Worker configuration.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://vite.dev/config/worker-options.html
 */

import { $obj } from '../../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';

/**
 * Configures workers.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Worker configuration.
 */
export default async ({ rollupConfig }) => {
    return {
        workerConfig: {
            format: 'es',
            plugins: () => [], // None at this time.
            rollupOptions: { ...$obj.omit(rollupConfig, ['input']) },
        },
    };
};
