/**
 * Vite config file.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://vitejs.dev/config/
 */
/* eslint-env es2021, node */

import tsAliases from '../../typescript/includes/import-aliases.mjs';

/**
 * Defines vite resolution aliases.
 */
const aliases = []; // Initialize aliases.

for (const [key, value] of Object.entries(tsAliases)) {
	aliases.push({ find: new RegExp(key), replacement: value });
}
export default aliases;
