/**
 * Prefresh config file.
 *
 * Prefresh is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@prefresh/vite
 */

import exclusions from '../../../bin/includes/exclusions.mjs';
import extensions from '../../../bin/includes/extensions.mjs';

/**
 * Configures Prefresh for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Prefresh configuration for Vite.
 */
export default async () => {
    return (await import('@prefresh/vite')).default({
        exclude: [
            ...new Set([
                ...exclusions.localIgnores, //
                ...exclusions.logIgnores,
                ...exclusions.backupIgnores,
                ...exclusions.patchIgnores,
                ...exclusions.editorIgnores,
                ...exclusions.toolingIgnores,
                ...exclusions.pkgIgnores,
                ...exclusions.vcsIgnores,
                ...exclusions.osIgnores,
                ...exclusions.dotIgnores,
                ...exclusions.dtsIgnores,
                ...exclusions.configIgnores,
                ...exclusions.lockIgnores,
                ...exclusions.devIgnores,
                ...exclusions.distIgnores,
                ...exclusions.docIgnores,
            ]),
        ],
        include: [
            '**/*.' +
                extensions.asBracedGlob([
                    ...extensions.byDevGroup.allJavaScriptReact, //
                    ...extensions.byDevGroup.allTypeScriptReact,
                ]),
        ],
    });
};
