/**
 * Stylelint config file.
 *
 * Stylelint is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://stylelint.io/user-guide/configure
 */
/* eslint-env es2021, node */

/**
 * Base config.
 */
const baseConfig = {
	plugins: [
		'stylelint-scss', //
		'stylelint-order',
	],
	extends: [
		'stylelint-config-standard-scss', //
		'stylelint-config-recess-order',
		'stylelint-config-prettier', // Must come last.
	],
	ignoreFiles: [
		'**/.git/**', //
		'**/dist/**',
		'**/.yarn/**',
		'**/vendor/**',
		'**/node_modules/**',
		'**/jspm_packages/**',
		'**/bower_components/**',
	],
	rules: {
		'indentation': 'tab',
		'no-duplicate-selectors': false,
		'selector-type-no-unknown': false,
		'no-descending-specificity': false,
		'selector-class-pattern': '^[_-]?[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'selector-id-pattern': '^[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'at-rule-no-unknown': [true, { ignoreAtRules: ['tailwind', 'apply', 'variants', 'responsive', 'screen'] }],
	},
};

/**
 * Composition.
 */
module.exports = {
	...baseConfig,
	overrides: [
		{
			files: ['**/*.scss'],

			plugins: [...baseConfig.plugins],
			extends: [...baseConfig.extends],
			ignoreFiles: [...baseConfig.ignoreFiles],

			customSyntax: 'postcss-scss',
			rules: {
				...baseConfig.rules,
				'scss/at-rule-no-unknown': baseConfig.rules['at-rule-no-unknown'],
			},
		},
		{
			files: ['**/*.css'],

			plugins: [...baseConfig.plugins],
			extends: [...baseConfig.extends],
			ignoreFiles: [...baseConfig.ignoreFiles],

			customSyntax: 'postcss-safe-parser',
			rules: { ...baseConfig.rules },
		},
	],
};
