/**
 * Stylelint config file.
 *
 * @note Stylelint is not aware of this config file's location.
 *
 * @see https://stylelint.io/user-guide/configure
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This entire file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

let commonRules = {};

module.exports = {
	plugins     : [
		'stylelint-scss',
	],
	extends     : [
		'stylelint-config-standard-scss',
		'stylelint-config-recess-order',
		'stylelint-config-prettier',
	],
	ignoreFiles : [
		'**/dist/**',
		'**/node_modules/**',
	],
	rules       : ( commonRules = {
		'indentation'               : 'tab',
		'no-duplicate-selectors'    : false,
		'selector-type-no-unknown'  : false,
		'no-descending-specificity' : false,
		'selector-class-pattern'    : '^[_-]?[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'selector-id-pattern'       : '^[a-z][a-z0-9]*(?:[_-]{1,2}[a-z0-9]+)*$',
		'at-rule-no-unknown'        : [ true, { ignoreAtRules : [ 'tailwind', 'apply', 'variants', 'responsive', 'screen' ] } ],
	} ),
	overrides   : [
		{
			files        : [ '**/*.scss' ],
			customSyntax : 'postcss-scss',
			rules        : {
				...commonRules,
				'scss/at-rule-no-unknown' : commonRules[ 'at-rule-no-unknown' ],
			},
		},
		{
			files        : [ '**/*.css' ],
			customSyntax : 'postcss-safe-parser',
			rules        : { ...commonRules },
		},
	],
};
