/**
 * Prefresh plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@prefresh/vite
 */

import pluginConfig from '@prefresh/vite';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures prefresh plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Prefresh plugin.
 */
export default async () => {
    return pluginConfig({
        exclude: [
            ...new Set([
                ...u.omit.localIgnores, //
                ...u.omit.logIgnores,
                ...u.omit.backupIgnores,
                ...u.omit.patchIgnores,
                ...u.omit.editorIgnores,
                ...u.omit.toolingIgnores,
                ...u.omit.pkgIgnores,
                ...u.omit.vcsIgnores,
                ...u.omit.osIgnores,
                ...u.omit.dotIgnores,
                ...u.omit.dtsIgnores,
                ...u.omit.configIgnores,
                ...u.omit.lockIgnores,
                ...u.omit.devIgnores,
                ...u.omit.distIgnores,
                ...u.omit.docIgnores,
            ]),
        ],
        include: [
            '**/*.' +
                u.exts.asBracedGlob([
                    ...u.exts.byDevGroup.allJavaScriptReact, //
                    ...u.exts.byDevGroup.allTypeScriptReact,
                ]),
        ],
    });
};
