/**
 * ES.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import globals from 'globals';

/**
 * Exports ES.
 */
export default {
    version: {
        year: 2022,
        lcnYear: 'es2022',
        ucnYear: 'ES2022',
        globals: globals.es2022,
    },
};
