/**
 * Extensions.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @internal This file is used by our Tailwind config file. Jiti, which is used by Tailwind to load ESM config files, doesn’t
 * support top-level await and does not support `import.meta.url`. Thus, we cannot use async functionality here, and we
 * cannot use our `u` (utilities). Please be sure to test any changes in this file against our Tailwind config file.
 */

import { $obj, $path } from '../../../../node_modules/@clevercanyon/utilities/dist/index.js';

/**
 * Adds leading dot to extensions.
 *
 * @param   exts Array of extensions.
 *
 * @returns      Array of extensions (with dot).
 */
const dot = (exts) => noDot(exts).map((ext) => '.' + ext);

/**
 * Strips leading dot from extensions.
 *
 * @param   exts Array of extensions.
 *
 * @returns      Array of extensions (not dot).
 */
const noDot = (exts) => [...new Set(exts)].map((ext) => ext.replace(/^\./u, ''));

/**
 * Converts an array of extensions into a braced glob.
 *
 * @param   exts Array of extensions.
 *
 * @returns      Extensions as a braced glob.
 *
 * @note Don’t use `{}` braces in TypeScript config files; i.e., incompatible.
 */
const asBracedGlob = (exts) => {
    exts = [...new Set(exts)]; // Unique.
    return (exts.length > 1 ? '{' : '') + noDot(exts).join(',') + (exts.length > 1 ? '}' : '');
};

/**
 * Converts an array of extensions into no-brace globstars.
 *
 * @param   exts Array of extensions.
 *
 * @returns      Extensions as no-brace globstars.
 */
const asNoBraceGlobstars = (exts) => {
    return noDot(exts).map((ext) => '**/*.' + ext);
};

/**
 * Converts an array of extensions into a regular expression fragment.
 *
 * @param   exts Array of extensions.
 *
 * @returns      Extensions as a regular expression fragment.
 */
const asRegExpFrag = (exts) => {
    exts = [...new Set(exts)]; // Unique.
    return (exts.length > 1 ? '(?:' : '') + noDot(exts).join('|') + (exts.length > 1 ? ')' : '');
};

/**
 * Defines module.
 */
const module = {
    /**
     * By canonical.
     */
    byCanonical: $obj.map(
        $obj.cloneDeep($path.extsByCanonical()), //
        (exts) => dot(exts),
        { byReference: true },
    ),

    /**
     * By VS Code lang (camelCase, includes `codeTextual`).
     */
    byVSCodeLang: $obj.map(
        $obj.cloneDeep($path.extsByVSCodeLang({ camelCase: true, enableCodeTextual: true })), //
        (exts) => dot(exts),
        { byReference: true },
    ),

    /**
     * By dev group.
     */
    byDevGroup: $obj.map(
        $obj.cloneDeep($path.jsTSExtsByDevGroup()), //
        (exts) => dot(exts),
        { byReference: true },
    ),

    /**
     * Utilities.
     */
    dot,
    noDot,
    asBracedGlob,
    asNoBraceGlobstars,
    asRegExpFrag,
};

/**
 * Tailwind content extensions.
 */
module.tailwindContent = [
    ...new Set([
        ...module.byVSCodeLang.mdx,
        ...module.byVSCodeLang.markdown,
        ...module.byVSCodeLang.html,

        ...module.byVSCodeLang.php,
        ...module.byVSCodeLang.asp,
        ...module.byVSCodeLang.ruby,
        ...module.byVSCodeLang.python,
        ...module.byVSCodeLang.perl,
        ...module.byVSCodeLang.shellscript,

        ...module.byDevGroup.allJavaScript,
        ...module.byDevGroup.allTypeScript,

        ...module.byVSCodeLang.xml, // e.g., SVGs.
    ]),
];
module.tailwindPrettierContent = [...module.tailwindContent];

/**
 * Comment anchors content extensions.
 */
module.commentAnchorsContent = [...module.tailwindContent];

/**
 * Extensions to try on import w/o extension.
 */
module.onImportWithNoExtensionTry = [...module.byDevGroup.allTypeScript, ...module.byDevGroup.allJavaScript];

/**
 * Exports extensions.
 */
export default module;
