/**
 * Node.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

/**
 * Exports node.
 */
export default {
    version: {
        previous: '20.9.0',
        current: '21.6.2',
        forwardCompat: ['22.9.0'],

        npm: {
            previous: '10.1.0',
            current: '10.2.4',
            forwardCompat: ['10.8.3'],
        },
    },
};
