/**
 * EJS plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/trapcodeio/vite-plugin-ejs
 */

import { createRequire } from 'node:module';
import path from 'node:path';
import { ViteEjsPlugin as pluginConfig } from 'vite-plugin-ejs';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures EJS plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       EJS plugin.
 */
export default async ({ mode, env }) => {
    return pluginConfig(
        {
            // EJS template data. We expose `$` object properties.

            $: {
                require: createRequire(import.meta.url), // `require()` fn.
                pkg: u.pkg(), // Current `./package.json` data.
                mode, // Current mode; e.g., `dev`, `prod`.
                env, // Current environment variables.
                projDir: u.projDir, // Project dir.
            },
        },
        {
            // EJS is enabled for `index.{html}` entry points.

            ejs: /* <https://o5p.me/wGv5nM> */ {
                strict: true, // JS strict mode.
                async: true, // Support await in EJS files.

                delimiter: '?', // <https://o5p.me/Qwu3af>.
                localsName: '$', // Shorter name for `locals`.
                outputFunctionName: 'echo', // For output in scriptlets.

                root: [u.srcDir], // For includes with an absolute path.
                views: /* For includes with a relative path — includes utilities. */ [
                    //
                    path.resolve(u.resourcesDir, './ejs-views'), // Our standard location for internal EJS views.
                    path.resolve(u.assetsDir, './ejs-views'), // Our standard location for distributed EJS views.
                ],
            },
        },
    );
};
