/**
 * Icons config file.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/unplugin-icons
 */

/**
 * Configures icons for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Icon configuration.
 */
export default async (/* {} */) => {
    return (await import('unplugin-icons/vite')).default({
        compiler: 'jsx',
        jsx: 'preact',
        scale: 1.2,
        defaultStyle: '',
        defaultClass: '',
    });
};
