/**
 * Terser config file.
 *
 * Terser is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://terser.org/docs/api-reference/#minify-options
 */

import esVersion from '../../../bin/includes/es-version.mjs';

/**
 * Configures terser for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Terser configuration.
 */
export default async (/* {} */) => {
    return {
        module: true,
        toplevel: true,
        ecma: esVersion.year,
        compress: { passes: 1 },
        format: { comments: false },
    };
};
