#!/usr/bin/env node
/**
 * Tailwind brand acquisition.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @internal This file is not run by Tailwind itself, so it is not subjected to the same limitations as our
 * other Tailwind config files. Therefore, it is perfectly OK to use a full set of `u` (utilities) in this file.
 */

import { $json } from '../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';
import u from '../../../../resources/utilities.mjs';

/**
 * Acquires app’s brand config; i.e., here within a separate CLI process.
 */
console.log(
    $json.stringify(
        await u.brandConfig({
            mode: process.argv[2],
            baseURL: process.argv[3],
        }),
        { pretty: true },
    ),
);
