/**
 * Cloudflare sockets plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

/**
 * Configures Cloudflare sockets plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Cloudflare sockets plugin.
 */
export default async ({ mode, command }) => {
    const virtualId = 'cloudflare:sockets';
    const resolvedVirtualId = '\0' + virtualId;

    return {
        name: 'vite-plugin-c10n-cloudflare-sockets',

        resolveId(id) {
            if ('dev' === mode && 'serve' === command && id === virtualId) {
                return '\0' + id;
            }
        },
        async load(id) {
            if ('dev' === mode && 'serve' === command && id === resolvedVirtualId) {
                return 'export default {};';
            }
        },
    };
};
