/**
 * MDX config file.
 *
 * MDX is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@mdx-js/rollup
 */

import path from 'node:path';
import exclusions from '../../../bin/includes/exclusions.mjs';
import extensions from '../../../bin/includes/extensions.mjs';

/**
 * Configures MDX for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX configuration for Vite.
 */
export default async ({ projDir }) => {
    return (await import('@mdx-js/rollup')).default({
        exclude: [
            ...new Set([
                ...exclusions.localIgnores, //
                ...exclusions.logIgnores,
                ...exclusions.backupIgnores,
                ...exclusions.patchIgnores,
                ...exclusions.editorIgnores,
                ...exclusions.toolingIgnores,
                ...exclusions.pkgIgnores,
                ...exclusions.vcsIgnores,
                ...exclusions.osIgnores,
                ...exclusions.dotIgnores,
                ...exclusions.dtsIgnores,
                ...exclusions.configIgnores,
                ...exclusions.lockIgnores,
                ...exclusions.devIgnores,
                ...exclusions.distIgnores,
                ...exclusions.docIgnores,
            ]),
        ],
        include: [
            '**/*.' +
                extensions.asBracedGlob([
                    ...extensions.byVSCodeLang.markdown, // Single default export only.
                    ...extensions.byVSCodeLang.mdx, // Default + potentially other exports.
                ]),
        ],
        ...(await (await import(path.resolve(projDir, './mdx.config.mjs'))).default()),
    });
};
