/**
 * MDX config file.
 *
 * MDX is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@mdx-js/rollup
 */

import { config } from './config.mjs';

/**
 * Configures MDX for esBuild dependency optimization.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX configuration for esBuild dependency optimization.
 */
export default async ({ projDir }) => {
    return (await import('@mdx-js/esbuild')).default(await config({ projDir }));
};
