/**
 * PostCSS config file.
 *
 * PostCSS is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
 */
/* eslint-env es2021, node */

const path = require('node:path');
const projDir = path.resolve(__dirname, '../../..');

module.exports = {
	plugins: {
		'tailwindcss': { config: path.resolve(projDir, './.tailwindrc.cjs') },
		'postcss-preset-env': { stage: 3 }, // Includes autoprefixer.
	},
};
