/**
 * PostCSS config file.
 *
 * PostCSS is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
 */

import path from 'node:path';
import { $fs } from '../../../node_modules/@clevercanyon/utilities.node/dist/index.js';

const __dirname = $fs.imuDirname(import.meta.url);
const projDir = path.resolve(__dirname, '../../..');

/**
 * Defines PostCSS configuration.
 */
export default async () => {
    /**
     * Composition.
     */
    return {
        plugins: {
            // SCSS is not configured here, as it’s already backed into Vite; {@see https://o5p.me/CAJNAF}.
            // To use `*.scss` files, just make sure the `sass` package is installed as a dev dependency.

            // Note: Sass runs before postCSS, and therefore cannot interpolate Tailwind `theme()` function calls.
            // i.e., Tailwind’s `theme()` function works, but don’t try to feed a response into an SCSS variable|fn.

            'tailwindcss': { config: path.resolve(projDir, './tailwind.config.mjs') },
            'postcss-preset-env': { stage: 3 }, // Includes autoprefixer.
            'postcss-variable-compress': {}, // Compresses variables.
        },
    };
};
