/**
 * Minify plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/zhuweiyou/vite-plugin-minify
 */

import { ViteMinifyPlugin as pluginConfig } from 'vite-plugin-minify';

/**
 * Configures minify plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Minify plugin; else `null` if n/a.
 */
export default async ({ minifyEnable }) => {
    if (!minifyEnable) {
        return null; // Not applicable.
    }
    return pluginConfig();
};
