/**
 * ESBuild config file.
 *
 * ESBuild is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://o5p.me/XOFuJp
 */

/**
 * Configures esbuild for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       ESBuild configuration.
 */
export default async (/* {} */) => {
    return {
        // See <https://o5p.me/Wk8Fm9>.
        jsx: 'automatic', // Matches TypeScript config.
        jsxImportSource: 'preact', // Matches TypeScript config.
        legalComments: 'none', // See <https://o5p.me/DZKXwX>.
    };
};
