#!/usr/bin/env node
/**
 * `$ madrun` CLI config.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

import events from './includes/events.mjs';

/**
 * `$ madrun` commands.
 */
export default async (/* {cmd, args, ctx} */) => {
	return {
		'envs': './dev/.files/bin/envs.mjs {{@}}',
		'install': './dev/.files/bin/install.mjs {{@}}',
		'update': './dev/.files/bin/update.mjs {{@}}',

		'dev': async ({ args }) => 'npx vite dev' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
		'preview': async ({ args }) => 'npx vite preview' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
		'build': async ({ args }) => 'npx vite build' + (args.mode ? '' : ' --mode=prod') + ' {{@}}',

		'tests': async ({ args }) => 'npx vitest' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
		'tests:ui': async ({ args }) => 'npx vitest --watch --ui' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',

		'jest': 'npx jest {{@}}', // Runs project Jest tests.
		'vitest': async ({ args }) => 'npx vitest' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
		'wrangler': 'CLOUDFLARE_API_TOKEN="${USER_CLOUDFLARE_TOKEN:-}" npx wrangler {{@}}',

		...events, // e.g., `on::madrun:default:new`.
	};
};
