/**
 * Rehype config file.
 *
 * Rehype is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/rehypejs/rehype/tree/main/packages/rehype-stringify#options
 */

import pluginStarryNight from '@microflash/rehype-starry-night';
import pluginAutolinkHeadings from 'rehype-autolink-headings';
import pluginSlug from 'rehype-slug';
import pluginAnchorsRelExternalNoFollow from './plugins/anchors/rel-external-nofollow.mjs';
import pluginFootnotesFixAnchors from './plugins/footnotes/fix-anchors.mjs';
import pluginFootnotesFixLabelSection from './plugins/footnotes/fix-label-section.mjs';
import pluginImagesLazy from './plugins/images/lazy.mjs';
import pluginStarryNightHeaderExts from './plugins/starry-night/header-exts.mjs';

/**
 * Defines Rehype configuration.
 */
export default async () => {
    /**
     * Composition.
     */
    return {
        settings: {}, // No settings at this time.
        plugins: [
            [pluginSlug, { prefix: '~' }], // Auto-generates heading IDs using heading text and counters.
            [pluginAutolinkHeadings, { content: { type: 'text', value: '#' } }], // Auto-links all headings.
            [pluginAnchorsRelExternalNoFollow], // Modifies external anchors, adding `rel="external nofollow"`, if applicable, for improved SEO.
            [pluginImagesLazy], // Modifies image tags without a `loading` attribute, making them `loading="lazy"` for improved performance.
            [pluginFootnotesFixAnchors], // Modifies `remark-gfm` footnote anchors, shortening ID references and enforcing a `~` prefix.
            [pluginFootnotesFixLabelSection], // Modifies `#footnote-label` section at bottom, generated by `remark-gfm` plugin.
            // Applies syntax highlighting. We also mix in our own custom header extensions.
            [pluginStarryNight, { headerExtensions: pluginStarryNightHeaderExts }],
        ],
    };
};
