/**
 * DTS config file.
 *
 * DTS is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/vite-plugin-dts
 */

/**
 * Configures DTS for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       DTS configuration.
 */
export default async ({ isSSRBuild, distDir }) => {
    return isSSRBuild
        ? null // No types for SSR builds.
        : (await import('vite-plugin-dts')).default({
              logLevel: 'error',
              outDir: distDir + '/types',
          });
};
