/**
 * Minify config file.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/zhuweiyou/vite-plugin-minify
 */

/**
 * Configures minification for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Minify configuration; else `null` if not applicable.
 */
export default async ({ minifyEnable }) => {
    return minifyEnable ? (await import('vite-plugin-minify')).ViteMinifyPlugin() : null;
};
